#!/bin/bash -euxo pipefail

# Save our current commit to use for comparison later
HEAD=$(git rev-parse HEAD)

# Pull down latest code
git pull origin main

# Update dependencies if package.json has changed
git diff --quiet $HEAD package.json >/dev/null || npm install --omit=dev --silent

# Reload unit files if any changes have been made to them
git diff --quiet $HEAD config/*.{service,timer} || sudo systemctl daemon-reload

# Always do a rebuild to regenerate the static pages
npm run build

# Reload or restart the server if there have been changes
git diff --quiet $HEAD src/server || sudo service pkmn.ai-server ${1:-reload}

# Reload NGINX if the config has changed
git diff --quiet $HEAD config/nginx.conf || sudo service nginx reload
